sonar.projectKey=colocation-com
sonar.projectName=Colocation.com
sonar.projectVersion=1.0

sonar.sources=src,templates
sonar.tests=tests
sonar.language=php

sonar.php.coverage.reportPaths=var/coverage.xml
sonar.php.tests.reportPath=var/tests.xml

sonar.exclusions=vendor/**,var/**,public/uploads/**,migrations/**
sonar.test.exclusions=tests/bootstrap.php

sonar.sourceEncoding=UTF-8
